version: '2'
services:
  web:
    image: amitasviper/movie_recommender_web
    container_name: flask_web_app
    ports:
      - "80:5000"
    depends_on:
      - postgres
      - elasticsearch
  postgres:
    image: amitasviper/movie_recommender_db
    container_name: postgres_instance
    ports:
      - "5432:5432"
  elasticsearch:
    image: amitasviper/movie_recommender_es
    container_name: elasticsearch_instance
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
